<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN65003994" failures="2" tests="2" name="Default test(failed)" time="5.447" errors="0" timestamp="2023-04-22T23:38:16 IST">
  <testcase classname="testCases.LoginDDT" name="login" time="0.748">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.LoginDDT.login(LoginDDT.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testCases.LoginDDT" name="login" time="0.572">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.LoginDDT.login(LoginDDT.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Default test(failed) -->
